// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export class AccessRequest {
    "id": string;
    "code": string;
    "ip": string;
    "userAgent": string;
    "createdAt": time$0.Time;
    "expiresAt": time$0.Time;

    /** Creates a new AccessRequest instance. */
    constructor($$source: Partial<AccessRequest> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("code" in $$source)) {
            this["code"] = "";
        }
        if (!("ip" in $$source)) {
            this["ip"] = "";
        }
        if (!("userAgent" in $$source)) {
            this["userAgent"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("expiresAt" in $$source)) {
            this["expiresAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccessRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): AccessRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccessRequest($$parsedSource as Partial<AccessRequest>);
    }
}

export class AccessSession {
    "id": string;
    "ip": string;
    "userAgent": string;
    "createdAt": time$0.Time;

    /** Creates a new AccessSession instance. */
    constructor($$source: Partial<AccessSession> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("ip" in $$source)) {
            this["ip"] = "";
        }
        if (!("userAgent" in $$source)) {
            this["userAgent"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccessSession instance from a string or object.
     */
    static createFrom($$source: any = {}): AccessSession {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccessSession($$parsedSource as Partial<AccessSession>);
    }
}

export enum Permission {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PermissionReadOnly = "readonly",
    PermissionUpload = "upload",
    PermissionManage = "manage",
};

export class PermissionOption {
    "value": Permission;
    "label": string;
    "description": string;

    /** Creates a new PermissionOption instance. */
    constructor($$source: Partial<PermissionOption> = {}) {
        if (!("value" in $$source)) {
            this["value"] = Permission.$zero;
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PermissionOption instance from a string or object.
     */
    static createFrom($$source: any = {}): PermissionOption {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PermissionOption($$parsedSource as Partial<PermissionOption>);
    }
}
