// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export enum Permission {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PermissionReadOnly = "readonly",
    PermissionUpload = "upload",
    PermissionManage = "manage",
};

export class PermissionOption {
    "value": Permission;
    "label": string;
    "description": string;

    /** Creates a new PermissionOption instance. */
    constructor($$source: Partial<PermissionOption> = {}) {
        if (!("value" in $$source)) {
            this["value"] = Permission.$zero;
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PermissionOption instance from a string or object.
     */
    static createFrom($$source: any = {}): PermissionOption {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PermissionOption($$parsedSource as Partial<PermissionOption>);
    }
}
