// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export class AccessRequest {
    /**
     * ID is an internal desktop approval handle. LAN browsers identify the
     * request with the lf_request cookie instead of receiving this value.
     */
    "id": string;
    "ip": string;
    "userAgent": string;
    "requestCount": number;
    "createdAt": time$0.Time;
    "lastSeenAt": time$0.Time;
    "expiresAt": time$0.Time;

    /** Creates a new AccessRequest instance. */
    constructor($$source: Partial<AccessRequest> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("ip" in $$source)) {
            this["ip"] = "";
        }
        if (!("userAgent" in $$source)) {
            this["userAgent"] = "";
        }
        if (!("requestCount" in $$source)) {
            this["requestCount"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("lastSeenAt" in $$source)) {
            this["lastSeenAt"] = null;
        }
        if (!("expiresAt" in $$source)) {
            this["expiresAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccessRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): AccessRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccessRequest($$parsedSource as Partial<AccessRequest>);
    }
}

export class AccessSession {
    /**
     * IP and UserAgent are display-only metadata for the desktop approval UI.
     * Validate treats the session cookie as a bearer token and does not bind it
     * to either value.
     */
    "id": string;
    "ip": string;
    "userAgent": string;
    "createdAt": time$0.Time;
    "expiresAt"?: time$0.Time | null;

    /** Creates a new AccessSession instance. */
    constructor($$source: Partial<AccessSession> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("ip" in $$source)) {
            this["ip"] = "";
        }
        if (!("userAgent" in $$source)) {
            this["userAgent"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccessSession instance from a string or object.
     */
    static createFrom($$source: any = {}): AccessSession {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccessSession($$parsedSource as Partial<AccessSession>);
    }
}

export enum AccessSessionLifetime {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AccessSession10Minutes = "10m",
    AccessSession30Minutes = "30m",
    AccessSession1Hour = "1h",
    AccessSession1Day = "24h",
    AccessSessionNever = "never",
};

export class AccessSessionLifetimeOption {
    "value": AccessSessionLifetime;
    "label": string;

    /** Creates a new AccessSessionLifetimeOption instance. */
    constructor($$source: Partial<AccessSessionLifetimeOption> = {}) {
        if (!("value" in $$source)) {
            this["value"] = AccessSessionLifetime.$zero;
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccessSessionLifetimeOption instance from a string or object.
     */
    static createFrom($$source: any = {}): AccessSessionLifetimeOption {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccessSessionLifetimeOption($$parsedSource as Partial<AccessSessionLifetimeOption>);
    }
}

export class Message {
    "id": string;
    "createdAt": time$0.Time;
    "clientId": string;
    "text": string;

    /** Creates a new Message instance. */
    constructor($$source: Partial<Message> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("clientId" in $$source)) {
            this["clientId"] = "";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Message instance from a string or object.
     */
    static createFrom($$source: any = {}): Message {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Message($$parsedSource as Partial<Message>);
    }
}

export enum Permission {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PermissionReadOnly = "readonly",
    PermissionUpload = "upload",
    PermissionManage = "manage",
};

export class PermissionOption {
    "value": Permission;
    "label": string;
    "description": string;

    /** Creates a new PermissionOption instance. */
    constructor($$source: Partial<PermissionOption> = {}) {
        if (!("value" in $$source)) {
            this["value"] = Permission.$zero;
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PermissionOption instance from a string or object.
     */
    static createFrom($$source: any = {}): PermissionOption {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PermissionOption($$parsedSource as Partial<PermissionOption>);
    }
}
