// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as share$0 from "../share/models.js";

export class Config {
    "sharedDir": string;
    "port": number;
    "permission": share$0.Permission;
    "accessApproval": boolean;
    "accessSessionLifetime": share$0.AccessSessionLifetime;
    "autoShare": boolean;
    "startAtLogin": boolean;
    "keepInTray": boolean;
    "showHiddenFiles": boolean;
    "language": string;

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {
        if (!("sharedDir" in $$source)) {
            this["sharedDir"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("permission" in $$source)) {
            this["permission"] = share$0.Permission.$zero;
        }
        if (!("accessApproval" in $$source)) {
            this["accessApproval"] = false;
        }
        if (!("accessSessionLifetime" in $$source)) {
            this["accessSessionLifetime"] = share$0.AccessSessionLifetime.$zero;
        }
        if (!("autoShare" in $$source)) {
            this["autoShare"] = false;
        }
        if (!("startAtLogin" in $$source)) {
            this["startAtLogin"] = false;
        }
        if (!("keepInTray" in $$source)) {
            this["keepInTray"] = false;
        }
        if (!("showHiddenFiles" in $$source)) {
            this["showHiddenFiles"] = false;
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Config($$parsedSource as Partial<Config>);
    }
}
