// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as share$0 from "../share/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export class LogEntry {
    "time": time$0.Time;
    "method": string;
    "path": string;
    "remote": string;
    "status": number;
    "action": string;
    "target"?: string;
    "targetPath"?: string;
    "detail"?: string;
    "error"?: string;

    /** Creates a new LogEntry instance. */
    constructor($$source: Partial<LogEntry> = {}) {
        if (!("time" in $$source)) {
            this["time"] = null;
        }
        if (!("method" in $$source)) {
            this["method"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("remote" in $$source)) {
            this["remote"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = 0;
        }
        if (!("action" in $$source)) {
            this["action"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): LogEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogEntry($$parsedSource as Partial<LogEntry>);
    }
}

export class RuntimeStatus {
    "running": boolean;
    "host": string;
    "port": number;
    "root": string;
    "permission": share$0.Permission;

    /** Creates a new RuntimeStatus instance. */
    constructor($$source: Partial<RuntimeStatus> = {}) {
        if (!("running" in $$source)) {
            this["running"] = false;
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("root" in $$source)) {
            this["root"] = "";
        }
        if (!("permission" in $$source)) {
            this["permission"] = share$0.Permission.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuntimeStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): RuntimeStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RuntimeStatus($$parsedSource as Partial<RuntimeStatus>);
    }
}
