// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    AppInfo,
    AppState,
    Capabilities,
    WindowInfo
} from "./models.js";
