// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as server$0 from "../server/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as share$0 from "../share/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export class AppInfo {
    "name": string;
    "version": string;
    "os": string;
    "osName": string;
    "osVersion": string;
    "arch": string;
    "locale": string;
    "systemTheme": string;
    "configPath": string;
    "window": WindowInfo;

    /** Creates a new AppInfo instance. */
    constructor($$source: Partial<AppInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("os" in $$source)) {
            this["os"] = "";
        }
        if (!("osName" in $$source)) {
            this["osName"] = "";
        }
        if (!("osVersion" in $$source)) {
            this["osVersion"] = "";
        }
        if (!("arch" in $$source)) {
            this["arch"] = "";
        }
        if (!("locale" in $$source)) {
            this["locale"] = "";
        }
        if (!("systemTheme" in $$source)) {
            this["systemTheme"] = "";
        }
        if (!("configPath" in $$source)) {
            this["configPath"] = "";
        }
        if (!("window" in $$source)) {
            this["window"] = (new WindowInfo());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): AppInfo {
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("window" in $$parsedSource) {
            $$parsedSource["window"] = $$createField9_0($$parsedSource["window"]);
        }
        return new AppInfo($$parsedSource as Partial<AppInfo>);
    }
}

export class AppState {
    "config": config$0.Config;
    "server": server$0.RuntimeStatus;
    "appInfo": AppInfo;
    "capabilities": Capabilities;
    "addresses": string[];
    "permissions": share$0.PermissionOption[];

    /** Creates a new AppState instance. */
    constructor($$source: Partial<AppState> = {}) {
        if (!("config" in $$source)) {
            this["config"] = (new config$0.Config());
        }
        if (!("server" in $$source)) {
            this["server"] = (new server$0.RuntimeStatus());
        }
        if (!("appInfo" in $$source)) {
            this["appInfo"] = (new AppInfo());
        }
        if (!("capabilities" in $$source)) {
            this["capabilities"] = (new Capabilities());
        }
        if (!("addresses" in $$source)) {
            this["addresses"] = [];
        }
        if (!("permissions" in $$source)) {
            this["permissions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppState instance from a string or object.
     */
    static createFrom($$source: any = {}): AppState {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType3;
        const $$createField3_0 = $$createType4;
        const $$createField4_0 = $$createType5;
        const $$createField5_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField0_0($$parsedSource["config"]);
        }
        if ("server" in $$parsedSource) {
            $$parsedSource["server"] = $$createField1_0($$parsedSource["server"]);
        }
        if ("appInfo" in $$parsedSource) {
            $$parsedSource["appInfo"] = $$createField2_0($$parsedSource["appInfo"]);
        }
        if ("capabilities" in $$parsedSource) {
            $$parsedSource["capabilities"] = $$createField3_0($$parsedSource["capabilities"]);
        }
        if ("addresses" in $$parsedSource) {
            $$parsedSource["addresses"] = $$createField4_0($$parsedSource["addresses"]);
        }
        if ("permissions" in $$parsedSource) {
            $$parsedSource["permissions"] = $$createField5_0($$parsedSource["permissions"]);
        }
        return new AppState($$parsedSource as Partial<AppState>);
    }
}

export class Capabilities {
    "startAtLogin": boolean;
    "tray": boolean;
    "openFolder": boolean;
    "systemThemeEvents": boolean;
    "windowState": boolean;

    /** Creates a new Capabilities instance. */
    constructor($$source: Partial<Capabilities> = {}) {
        if (!("startAtLogin" in $$source)) {
            this["startAtLogin"] = false;
        }
        if (!("tray" in $$source)) {
            this["tray"] = false;
        }
        if (!("openFolder" in $$source)) {
            this["openFolder"] = false;
        }
        if (!("systemThemeEvents" in $$source)) {
            this["systemThemeEvents"] = false;
        }
        if (!("windowState" in $$source)) {
            this["windowState"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Capabilities instance from a string or object.
     */
    static createFrom($$source: any = {}): Capabilities {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Capabilities($$parsedSource as Partial<Capabilities>);
    }
}

export class ErrorPayload {
    "error": string;
    "params"?: { [_ in string]?: any };

    /** Creates a new ErrorPayload instance. */
    constructor($$source: Partial<ErrorPayload> = {}) {
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ErrorPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): ErrorPayload {
        const $$createField1_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("params" in $$parsedSource) {
            $$parsedSource["params"] = $$createField1_0($$parsedSource["params"]);
        }
        return new ErrorPayload($$parsedSource as Partial<ErrorPayload>);
    }
}

export class Notice {
    "id": string;
    "level": NoticeLevel;
    "source": NoticeSource;
    "error"?: ErrorPayload | null;
    "message"?: string;
    "createdAt": time$0.Time;

    /** Creates a new Notice instance. */
    constructor($$source: Partial<Notice> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("level" in $$source)) {
            this["level"] = NoticeLevel.$zero;
        }
        if (!("source" in $$source)) {
            this["source"] = NoticeSource.$zero;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Notice instance from a string or object.
     */
    static createFrom($$source: any = {}): Notice {
        const $$createField3_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField3_0($$parsedSource["error"]);
        }
        return new Notice($$parsedSource as Partial<Notice>);
    }
}

export enum NoticeLevel {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    NoticeInfo = "info",
    NoticeSuccess = "success",
    NoticeWarning = "warning",
    NoticeError = "error",
};

export enum NoticeSource {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    NoticeSourceCommand = "command",
    NoticeSourceStartup = "startup",
    NoticeSourceSystem = "system",
};

export class WindowInfo {
    "x": number;
    "y": number;
    "width": number;
    "height": number;
    "maximised": boolean;
    "minimised": boolean;
    "fullscreen": boolean;

    /** Creates a new WindowInfo instance. */
    constructor($$source: Partial<WindowInfo> = {}) {
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }
        if (!("maximised" in $$source)) {
            this["maximised"] = false;
        }
        if (!("minimised" in $$source)) {
            this["minimised"] = false;
        }
        if (!("fullscreen" in $$source)) {
            this["fullscreen"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): WindowInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowInfo($$parsedSource as Partial<WindowInfo>);
    }
}

// Private type creation functions
const $$createType0 = WindowInfo.createFrom;
const $$createType1 = config$0.Config.createFrom;
const $$createType2 = server$0.RuntimeStatus.createFrom;
const $$createType3 = AppInfo.createFrom;
const $$createType4 = Capabilities.createFrom;
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = share$0.PermissionOption.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $Create.Map($Create.Any, $Create.Any);
const $$createType9 = ErrorPayload.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
