package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
)

func main() {
	root, err := projectRoot()
	if err != nil {
		panic(err)
	}
	localesDir := filepath.Join(root, "locales")
	outPath := filepath.Join(root, "internal", "i18n", "catalog_gen.go")

	languages := []string{"en", "zh-CN"}
	catalog := make(map[string]map[string]string, len(languages))
	for _, language := range languages {
		dict, err := readDictionary(filepath.Join(localesDir, language+".json"))
		if err != nil {
			panic(err)
		}
		catalog[language] = dict
	}

	source, err := renderCatalog(catalog, languages)
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile(outPath, source, 0644); err != nil {
		panic(err)
	}
}

func projectRoot() (string, error) {
	wd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(wd, "go.mod")); err == nil {
			return wd, nil
		}
		parent := filepath.Dir(wd)
		if parent == wd {
			return "", fmt.Errorf("go.mod not found")
		}
		wd = parent
	}
}

func readDictionary(path string) (map[string]string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var dict map[string]string
	if err := json.Unmarshal(data, &dict); err != nil {
		return nil, err
	}
	return dict, nil
}

func renderCatalog(catalog map[string]map[string]string, languages []string) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by tools/geni18n; DO NOT EDIT.\n\n")
	buf.WriteString("package i18n\n\n")
	buf.WriteString("var dictionaries = map[string]map[string]string{\n")
	for _, language := range languages {
		buf.WriteString("\t")
		buf.WriteString(strconv.Quote(language))
		buf.WriteString(": {\n")

		keys := make([]string, 0, len(catalog[language]))
		for key := range catalog[language] {
			keys = append(keys, key)
		}
		sort.Strings(keys)
		for _, key := range keys {
			buf.WriteString("\t\t")
			buf.WriteString(strconv.Quote(key))
			buf.WriteString(": ")
			buf.WriteString(strconv.Quote(catalog[language][key]))
			buf.WriteString(",\n")
		}

		buf.WriteString("\t},\n")
	}
	buf.WriteString("}\n")
	return format.Source(buf.Bytes())
}
